/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbdrennequinepolis;

/**
 *
 * @author Romain
 */
public class DialogLogin extends javax.swing.JDialog
{
    private String _login = null;
    
    /**
     * Creates new form DialogLogin
     */
    public DialogLogin(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    public String getLogin()
    {
        return _login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLoginBtn = new javax.swing.JButton();
        jLoginBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Identification...");

        jLoginBtn.setText("Valider");
        jLoginBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLoginBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Veuillez entrer votre login");

        jCancelBtn.setText("Annuler");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLoginBox))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginBtn)
                    .addComponent(jCancelBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // CHOIX LOGIN
    private void jLoginBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jLoginBtnActionPerformed
    {//GEN-HEADEREND:event_jLoginBtnActionPerformed
        if (jLoginBox.getText().isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous ne pouvez pas choisir un login vide.");
        }
        else
        {
            _login = jLoginBox.getText();
            setVisible(false);
        }
    }//GEN-LAST:event_jLoginBtnActionPerformed
    // ANNULER
    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCancelBtnActionPerformed
    {//GEN-HEADEREND:event_jCancelBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jCancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jLoginBox;
    private javax.swing.JButton jLoginBtn;
    // End of variables declaration//GEN-END:variables
}
